version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.13.0-stretch-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn --version
      - run: yarn
      - run: yarn test
